# Generated by Django 4.0.3 on 2022-03-18 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('feeds', '0002_feed_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
